# Generated by Django 6.0.1 on 2026-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_aboutus_forwhom_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['order'], 'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='forwhom',
            options={'ordering': ['order'], 'verbose_name': 'Kimlar uchun', 'verbose_name_plural': 'Kimlar uchun'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Maxfiylik siyosati', 'verbose_name_plural': 'Maxfiylik siyosati'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': 'Testimoniyal', 'verbose_name_plural': 'Testimoniyallar'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap ikonka yoki emoji', max_length=100, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='Maxfiylik siyosati', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
