# Generated by Django 6.0.1 on 2026-01-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='emlakuzinfo@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+998 (20) 017-57-53', max_length=50)),
                ('address', models.TextField(default='123 Fintech Avenue, Suite 400\nSan Francisco, CA 94105, USA')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
