# Generated by Django 6.0.1 on 2026-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Full content of the blog')),
                ('image', models.ImageField(upload_to='blog/')),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('date', models.DateField()),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
