# Generated by Django 6.0.1 on 2026-01-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBlog',
            fields=[
            ],
            options={
                'verbose_name': 'Blogs And Articles (Featured)',
                'verbose_name_plural': 'Blogs And Articles (Featured)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blog',),
        ),
        migrations.CreateModel(
            name='RegularBlog',
            fields=[
            ],
            options={
                'verbose_name': 'Latest Blogs, News & Articles',
                'verbose_name_plural': 'Latest Blogs, News & Articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blog',),
        ),
    ]
