# Generated by Django 6.0.1 on 2026-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='Available: Calendar, Users, TrendingUp, Wallet, BarChart3, etc.', max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('bg_color', models.CharField(default='bg-blue-50', max_length=50)),
                ('text_color', models.CharField(default='text-blue-600', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
